# Generated by Django 5.1.7 on 2025-08-23 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_is_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizinfo',
            name='score',
        ),
    ]
