# Generated by Django 5.1.7 on 2025-08-31 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_quizinfo_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizoption',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
