# Generated by Django 5.1.7 on 2025-08-31 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_quizoption_explanation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizoption',
            name='explanation',
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
